"""Column lists, declared once.

There used to be three copies of "the place columns" — in `place_fields`,
`search` and `accounts_store` — and they had drifted apart: one carried
`source_url`, another did not. They describe the same row, so they are one list.

`geom` and `embedding` are never selected: the first is generated by Postgres
from `lat`/`lon`, the second is a 384-float vector that no list needs.
"""

from __future__ import annotations

PLACE_COLUMNS: tuple[str, ...] = (
    "id",
    "name",
    "description",
    "category",
    "blurb",
    "fun_fact",
    "fun_facts",
    "links",
    "opening_hours",
    "ticket_price",
    "visit_minutes",
    "district",
    "town",
    "lat",
    "lon",
    "source_url",
    "category_source",
    "photo_url",
    "photo_author",
    "photo_license",
    "photo_source",
    "created_at",
)

PLACE_SELECT = ", ".join(PLACE_COLUMNS)

# `areas.geom` is a multipolygon the runtime never reads — resolution is by name.
AREA_COLUMNS: tuple[str, ...] = (
    "id",
    "code",
    "name_ru",
    "name_en",
    "aliases",
    "kind",
    "source",
    "license",
    "created_at",
)

AREA_SELECT = ", ".join(AREA_COLUMNS)

# What a caller may write through the place repository. Everything else is
# generated (`id`, `geom`), derived (`embedding`, `photo_*`), or owned by the
# seed and the curated-category guard (`category_source`).
PLACE_WRITE_COLUMNS: tuple[str, ...] = (
    "name",
    "lat",
    "lon",
    "source_url",
    "category",
    "town",
    "district",
    "blurb",
    "fun_fact",
    "visit_minutes",
    "opening_hours",
    "ticket_price",
)

# A user as the admin surface may see one — deliberately without the hash.
USER_COLUMNS: tuple[str, ...] = (
    "id",
    "email",
    "display_name",
    "role",
    "client_id",
    "created_at",
    "updated_at",
    "last_login_at",
)

USER_SELECT = ", ".join(USER_COLUMNS)

# Only the login lookup asks for the hash, and it must never leave the store.
USER_SECRET_SELECT = f"{USER_SELECT}, password_hash"
