"""Alembic environment for the Grodno schema.

The DSN comes from ``core.config.settings.DSN`` (the ``DATABASE_URL``
environment variable, with the localhost default) — never from alembic.ini, so
there is one place a deployment's database address is read. Importing
``core.config`` pulls in nothing beyond the standard library: no planner, no
agent, no store, so migrations stay runnable wherever the package is.
"""

from __future__ import annotations

import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

# Make `core` importable no matter how alembic was invoked (console script,
# `python -m`, or `make`). env.py lives at backend/db/alembic/env.py.
BACKEND_DIR = Path(__file__).resolve().parents[2]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from core.config import settings  # noqa: E402

config = context.config

# psycopg (v3) is the only driver installed; name it explicitly so an online
# run works instead of SQLAlchemy reaching for psycopg2.
dsn = settings.DSN
if dsn.startswith("postgresql://"):
    dsn = "postgresql+psycopg://" + dsn[len("postgresql://") :]
config.set_main_option("sqlalchemy.url", dsn)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The schema is hand-written SQL (raw op.execute), not autogenerated from
# models, so there is no metadata to diff against.
target_metadata = None


def run_migrations_offline() -> None:
    """Emit the SQL for `alembic upgrade ... --sql`, without a connection."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Apply the migrations against a live database."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
